{{- if or .Values.app.appKey.value .Values.database.password.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "databasement.fullname" . }}
  labels:
    {{- include "databasement.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.app.appKey.value (not .Values.app.appKey.fromSecret) }}
  app-key: {{ .Values.app.appKey.value | b64enc | quote }}
  {{- end }}
  {{- if and .Values.database.password.value (not .Values.database.password.fromSecret) (ne .Values.database.connection "sqlite") }}
  db-password: {{ .Values.database.password.value | b64enc | quote }}
  {{- end }}
{{- end }}
